export const TEST_LIST_REQUEST = "TEST_LIST_REQUEST";
export const TEST_LIST_SUCCESS = "TEST_LIST_SUCCESS";
export const TEST_LIST_FAIL = "TEST_LIST_FAIL";

export const TEST_DETAILS_REQUEST = "TEST_DETAILS_REQUEST";
export const TEST_DETAILS_SUCCESS = "TEST_DETAILS_SUCCESS";
export const TEST_DETAILS_FAIL = "TEST_DETAILS_FAIL";

export const TEST_CREATE_REQUEST = "TEST_CREATE_REQUEST";
export const TEST_CREATE_SUCCESS = "TEST_CREATE_SUCCESS";
export const TEST_CREATE_FAIL = "TEST_CREATE_FAIL";
export const TEST_CREATE_RESET = "TEST_CREATE_RESET";

export const TEST_UPDATE_REQUEST = "TEST_UPDATE_REQUEST";
export const TEST_UPDATE_SUCCESS = "TEST_UPDATE_SUCCESS";
export const TEST_UPDATE_FAIL = "TEST_UPDATE_FAIL";
export const TEST_UPDATE_RESET = "TEST_UPDATE_RESET";

export const TEST_DELETE_REQUEST = "TEST_DELETE_REQUEST";
export const TEST_DELETE_SUCCESS = "TEST_DELETE_SUCCESS";
export const TEST_DELETE_FAIL = "TEST_DELETE_FAIL";

export const TEST_TOP_RATED_REQUEST = "TEST_TOP_RATED_REQUEST";
export const TEST_TOP_RATED_SUCCESS = "TEST_TOP_RATED_SUCCESS";
export const TEST_TOP_RATED_FAIL = "TEST_TOP_RATED_FAIL";

export const TEST_FEATURED_REQUEST = "TEST_FEATURED_REQUEST";
export const TEST_FEATURED_SUCCESS = "TEST_FEATURED_SUCCESS";
export const TEST_FEATURED_FAIL = "TEST_FEATURED_FAIL";

export const ENROLL_TEST_REQUEST = "ENROLL_TEST_REQUEST";
export const ENROLL_TEST_SUCCESS = "ENROLL_TEST_SUCCESS";
export const ENROLL_TEST_FAIL = "ENROLL_TEST_FAIL";

export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAIL = "REVIEW_CREATE_FAIL";
export const REVIEW_CREATE_RESET = "REVIEW_CREATE_RESET";

export const CHECK_ANSWERS_REQUEST = "CHECK_ANSWERS_REQUEST";
export const CHECK_ANSWERS_SUCCESS = "CHECK_ANSWERS_SUCCESS";
export const CHECK_ANSWERS_FAIL = "CHECK_ANSWERS_FAIL";
export const CHECK_ANSWERS_RESET = "CHECK_ANSWERS_RESET";
